source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'Ertegi' do
    	pod 'FolioReaderKit'
    	pod 'Firebase'
        pod ‘Firebase/Core’
        pod 'FirebaseUI/Storage'
        pod ’SJSegmentedScrollView’, '1.3.6'
        pod 'SVProgressHUD'
end


